lib/src/components/arm/arm.dart, lib/src/components/base/base.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/sensor/sensor.dart, lib/src/components/servo/servo.dart, lib/src/domain/auth_rdk/service/auth_api_service.dart, lib/src/domain/web_rtc/web_rtc_client/web_rtc_client_connection.dart, lib/src/resource/base.dart, lib/src/resource/manager.dart, test/unit_test/domain/sensor/model/get_readings_response_to_viam_sensor_readings_mapper_test.dart
This is a dart style guide nit pr. Cleaning up some warnings dart is generating about double quotes, where we ought to [prefer single quotes](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-single-quotes-for-strings).
We could configure to prefer double quotes, I don't have a strong preference either way, just getting things in line with current linter configuration for now.
=> prefer single quote

example/viam_example_app/.vscode/settings.json, example/viam_example_app/analysis_options.yaml
This PR pulls in the lint and analysis settings from the SDK into the nested example project.
I like to run the example project from VS code by opening that project in its own window, I was running into inconsistencies in dart formatting the same file from the example project vs code window and the SDK vs code window, this resolves those inconsistencies in the auto formatting on save. As well as aligns the lint errors / warning that will be surfaced.
=> align example and sdk lint & analysis settings

lib/src/components/motor/client.dart, lib/src/components/motor/motor.dart
Renaming some methods in motor to follow dart guidelines.
Also some misc formatting changes were automatically included, these are no harm and should stop showing up now that i've dialed in analysis settings in the example app.
=> Motor Method Rename

example/viam_example_app/lib/screens/stream.dart, lib/src/components/camera/camera.dart, lib/src/components/camera/client.dart
Rename camera methods to follow dart guidelines.
Also included driveby fixing warning about not have a return type on `deactivate()`
=> Rename Camera Methods

example/viam_example_app/lib/screens/sensor.dart, lib/src/components/movement_sensor/client.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/sensor/client.dart, lib/src/components/sensor/sensor.dart
renaming methods in sensor & movement sensor to match dart style guide. (Avoid starting method names with 'get')
=> Sensor & Movement Sensor rename

.github/workflows/test.yaml, analysis_options.yaml, example/viam_example_app/lib/screens/stream.dart, lib/src/components/arm/service.dart, lib/src/components/base/client.dart, lib/src/components/base/service.dart, lib/src/components/board/board.dart, lib/src/components/board/client.dart, lib/src/components/board/service.dart, lib/src/components/motor/service.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/sensor/service.dart, lib/src/components/servo/service.dart, lib/src/domain/movement/service/viam_movement_service.dart, lib/src/domain/sensor/service/viam_sensor_service.dart, lib/src/media/image.dart, lib/src/resource/manager.dart, lib/src/robot/client.dart, lib/src/utils.dart, test/unit_test/components/base_test.dart, test/unit_test/components/servo_test.dart
added lint rule prefer_final_locals
> Declaring variables as final when possible is a good practice because it helps avoid accidental reassignments and allows the compiler to do optimizations.
https://dart-lang.github.io/linter/lints/prefer_final_locals.html
Also removed some unnecessary type annotations - https://dart.dev/effective-dart/design#types
> Don’t annotate locals and generic invocations unless you need to.
=> Prefer final locals

lib/src/components/movement_sensor/service.dart
Quick fix to update the names of parameters in the movement sensor
caught by https://github.com/viamrobotics/viam-flutter-sdk/actions/runs/5135209703/jobs/9240317699
the names changed in the most recent protos update and I didn't catch it before merging.
=> RSDK-3127 - update named parameters in movement sensor

.github/workflows/test.yaml, example/viam_example_app/lib/screens/stream.dart, lib/src/media/stream/client.dart, lib/src/robot/client.dart, lib/src/widgets/widgets.dart, lib/viam_sdk.dart
Because the webrtc peer is shared across the entire app, when each `StreamClient` would call `_channel.rtcPeerConnection.onAddStream`, it would overwrite any existing `onAddStream` definition. This made it such that whatever `StreamClient` was initialized last would be the one to control the peer connection. 
So I created a manager which will be the only object that manages all `onAddStream` events. It then saves those streams and can create/return a `StreamClient` when requested.
=> [RSDK-3762] Add stream manager

lib/src/components/arm/client.dart, lib/src/components/base/client.dart, lib/src/components/board/client.dart, lib/src/components/camera/client.dart, lib/src/components/gantry/client.dart, lib/src/components/motor/client.dart, lib/src/components/movement_sensor/client.dart, lib/src/components/sensor/client.dart, lib/src/components/servo/client.dart, lib/src/resource/base.dart, lib/src/robot/client.dart, test/unit_test/components/movement_sensor_test.dart
This PR adds robot reconnection logic, I copied the logic from our python SDK, so it ought to be very similar to that.
There are a couple of fly by's included here, i will call them out below.
Some follow up work will be reworking our stream client to reconnect as well. this is under construction currently in [this](https://github.com/viamrobotics/viam-flutter-sdk/pull/53) - i will address in a follow up.
=> RSDK-3192 - Add robot reconnection logic

lib/src/media/stream/client.dart, lib/src/rpc/dial.dart
There was a bug where navigating to a camera stream page, then leaving, then coming back wouldn't properly show the stream. 
Turns out, this was due to an extremely subtle bug caused by the way we were originally dialing. Long story short, we were creating offers that contradicted each other, putting the webrtc streams in a mismatched state. The streaming server saw this weird state and set the client to inactive, so we never got updated when a new stream got added (for the second navigation back to camera).
=> [RSDK 3804] Fix webrtc streaming

example/viam_example_app/lib/screens/stream.dart, lib/src/robot/sessions_client.dart, pubspec.yaml
fixing some misc things that have come up in the SDK / example app.
1. the stream view would crash the app upon leaving it. changed it to use our cameraStreamViewWidget, it no longer crashes.
Before:
After:
https://github.com/viamrobotics/viam-flutter-sdk/assets/22106496/0ee4ac19-7cf5-4384-a292-323d1f04febf
2. GRPC was upgraded to 3.2.3, I was using version 3.2.0 locally and it was causing compile errors because of our const constructors on GRPC errors.
3. bumped the session heartbeat time down to 1.8x the default from 5x. we it was failing too often with that high amount of calls.
4. started a new session upon failing.
=> misc cleanups

lib/widgets/button.dart, lib/widgets/camera_stream.dart, lib/widgets/joystick.dart, lib/widgets/resources/base.dart, lib/widgets/resources/board.dart, lib/widgets/resources/sensor.dart, test/test_utils.dart, test/widget_tests/sensor_widget_test.dart
Documentation and tests for sensor widget
=> [RSDK-4265] Sensor widget tests

lib/src/media/stream/client.dart, lib/src/robot/client.dart, lib/widgets/camera_stream.dart
Camera streams now automatically reestablish after a loss and regain of connection.
=> Reconnect camera streams

lib/src/robot/client.dart
It's possible that the previous way for reconnecting would attempt to reconnect multiple times while other reconnection attempts were already in flight.
I've changed the functionality to use a boolean check instead of canceling timers in order to break out of potential cycles.
=> Fix where reconnection might've gotten stuck in a loop

lib/src/media/stream/client.dart, lib/src/robot/client.dart, lib/widgets/camera_stream.dart
Close camera streams properly -- when there are no more listeners.
We reuse camera streams. Whenever someone asks for a stream, we return a cached copy if available. This stream might be new, cached and open, cached and previously closed (needs to be reopened), etc. We don't want the implementer to have to think about this. They should be able to call `close` whenever they are done, and we should figure out if it's time to actually close the stream (imagine they have multiple views with the same stream open, they should be able to close one without closing all).
This PR basically says, once there are no more subscribers to this stream, then close it for real. And finally, upon closing the robot, release all resources.
=> Close camera streams on robot close and when there are no more listeners

lib/src/components/arm/arm.dart, lib/src/components/arm/client.dart, lib/src/components/arm/service.dart, lib/widgets/button.dart, lib/widgets/resources/arm.dart, lib/widgets/resources/base.dart, test/unit_test/components/arm_test.dart
New arm widget.
Also, update buttons so we can actually have small sizes.
=> Arm widget

example/viam_robot_example_app/lib/main.dart, example/viam_robot_example_app/lib/screens/movement_sensor.dart, lib/widgets.dart, lib/widgets/refreshable_data_table.dart, lib/widgets/resources/arm.dart, lib/widgets/resources/base.dart, lib/widgets/resources/board.dart, lib/widgets/resources/gripper.dart, lib/widgets/resources/motor.dart, lib/widgets/resources/sensor.dart, lib/widgets/resources/servo.dart, test/widget_tests/refreshable_data_table_test.dart
Since `MovementSensor` is no longer a sensor type, we can't just reuse the `SensorWidget` like we used to. So I created a new data table to reuse across sensors and movement sensors and anything else that provides a map.
flyby: change the `{Key? key}` to `{super.key}`
=> Add new data table

README.md, lib/src/errors.dart, lib/src/exceptions.dart, lib/src/rpc/dial.dart, lib/src/rpc/web_rtc/web_rtc_transport_stream.dart
`errors` should be called `exceptions` when they can be handled by the user.
Also, this adds a new exception type to differentiate errors in mDNS: whether the robot was local vs other issues
=> Add new exception type for mdns

Makefile, example/viam_example_app/macos/Runner.xcodeproj/project.pbxproj, example/viam_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/app/data.dart, lib/src/utils.dart, lib/src/viam_sdk.dart, lib/src/viam_sdk_impl.dart, test/unit_test/app/data_client_test.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart, test/unit_test/utils/utils_test.dart
Also:
- rebuild mocks when running tests
- update utils to return `null` instead of `pb.NullValue` when converting structs to native
- add ability to specify service hosts (e.g. app.viam.dev)
=> Add SQL and MQL tabular data query

lib/widgets/resources/motor.dart
On Plus/Max sized iphones, the call to set state after awaiting setPower would happen sometimes after the call to stop had gone through, causing the slider to stick after release, even when the toggle to stop after release was enabled.
Moving the setState to before the awaited method calls fixes this issue.
I considered making the calls to setPower and stop `unawaited()` - but then we'd lose our error handling from the try catch.
We could also use the older convention of not using async/await and instead use the Future.onError() callback, to populate the error object. But I opted for using async and await because they are more idiomatic.
=> APP-3318 - Fix sticky motor slider

lib/widgets/joystick.dart
I added a perhaps too lengthy comment describing some of the thoughts on this issue in the code, I will explain here as well.
Essentially things tend to work well in normal network conditions, but as soon as the client is in spotty conditions, not enough to end the session but enough to garble the order of some calls or have some not make it through, the joystick widget tends to not auto stop not upon touch release and the base will continue to move in whatever the last command was.
My first thought was to shorten the sessions heartbeat interval, but that is configured per robot and not per client.
So I ended up tracking the touch locally in the widgets state and sending a stop command if the base is still moving but touch has been released, I check 100 milliseconds after each call.
If …
=> base auto stop bug fix

example/viam_example_app/.metadata, example/viam_example_app/ios/Runner.xcodeproj/project.pbxproj, example/viam_example_app/ios/Runner.xcworkspace/contents.xcworkspacedata, example/viam_example_app/ios/Runner/Info.plist, example/viam_example_app/lib/login_screen.dart, example/viam_example_app/pubspec.yaml, example/viam_example_app/windows/flutter/generated_plugin_registrant.cc, example/viam_example_app/windows/flutter/generated_plugins.cmake, example/viam_robot_example_app/ios/Runner/Info.plist, example/viam_robot_example_app/lib/main.dart, lib/src/media/stream/client.dart, lib/src/rpc/dial.dart, pubspec.yaml
Quite a bit of misc things going on in this PR - I will try and call them out.
Upgrading flutter_webrtc to latest because: https://github.com/flutter-webrtc/flutter-webrtc/issues/1428
upgrading bonsoir to latest because: https://github.com/Skyost/Bonsoir/issues/57 has been resolved
shorten mDNS scan timeout (this was the main thing lengthening connection times, whoops!).
add try catch for camera stream exception i kept hitting.
add comments for .env setup
=> improve webrtc connection times & misc improvements

example/viam_example_app/ios/Podfile, example/viam_robot_example_app/ios/Podfile, example/viam_robot_example_app/ios/Runner.xcodeproj/project.pbxproj, example/viam_robot_example_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/viam_robot_example_app/ios/Runner/Info.plist, example/viam_robot_example_app/lib/main.dart, example/viam_robot_example_app/lib/screens/base.dart, example/viam_robot_example_app/lib/screens/board.dart, example/viam_robot_example_app/lib/screens/gripper.dart, example/viam_robot_example_app/lib/screens/motor.dart, example/viam_robot_example_app/lib/screens/movement_sensor.dart, example/viam_robot_example_app/lib/screens/power_sensor.dart, example/viam_robot_example_app/lib/screens/sensor.dart, example/viam_robot_example_app/lib/screens/servo.dart, example/viam_robot_example_app/lib/screens/stream.dart, example/viam_robot_example_app/pubspec.yaml, example/viam_robot_example_app/windows/flutter/generated_plugin_registrant.cc, example/viam_robot_example_app/windows/flutter/generated_plugins.cmake, lib/src/rpc/dial.dart
I was looking into our example code and noticed some quick improvements.
The largest change is pulling out some packages we used in the robot example - this simplifies the code and we're only using vanilla flutter widgets now so it should be more clear to the average reader what is unique to our package and what is not.
Was looking into a mDNS dial failure i was getting and realized we were missing an `await` in the mDNS flow.
Also got our Podfile all pointing to the same iOS minimum version & included mDNS entitlements in the robot example info.plist.
tested locally and both examples still compile and run for me.
=> Refactor robot example

lib/widgets/camera_stream.dart
this issue came up again and I finally wanted to put it to rest.
I combed through the webRTC examples where they support web and they didn't have to do anything different to handle the RTCVideoStream for web vs other platforms.
The only difference I noticed was the setter they used for the srcObject. I tried changing it in our code to what they used and now video works on web as well as mobile platforms.
https://github.com/viamrobotics/viam-flutter-sdk/assets/22106496/c25f7673-285d-41b1-8007-f5549b1d8e3c
=> RSDK-5424 - fix video stream on flutter web

lib/src/app/app.dart, test/unit_test/app/app_client_test.dart
wrapping the newRobot call with `newMachine`.
=> RSDK-5953 - add newMachine wrapper

lib/widgets/resources/board.dart
[Ticket](https://viam.atlassian.net/browse/RSDK-6116)
In this PR, I modified the board card to refresh board readings every second just like we do for the sensor readings.
=> RSDK-6116: Mobile app should auto refresh board's analog readings

lib/src/components/board/board.dart, lib/src/components/board/client.dart, lib/src/components/board/service.dart, test/unit_test/components/board_test.dart
Implements the StreamTicks board API. also tested with code samples client script.
=> RSDK-7045 Implement StreamTicks 

lib/widgets/refreshable_data_table.dart, pubspec.yaml
opened up an old project and had a conflict with this package, realized there is no reason we need it in the SDK itself, was only used for one helper function.
widget still looks good
=> remove intl dependency

lib/src/rpc/dial.dart
https://viam.atlassian.net/browse/RSDK-6515
Adds a `timeout` field to `DialOptions` that defaults to 10s. Adds a few basic metrics to dialing collected through debug logs.
mDNS does not seem to work well with the flutter SDK, so I disabled it in testing. Note that mDNS is also disabled in the RC app, too, as its apparent advantage in "limited connectivity" situations is not really relevant with a phone, as phones are usually operating with _some_ kind of network connection.
Here are some statistics I collected with the new instrumentation that led me to choose a 10s default dial timeout (about 10x "ICE connected" times across different subnets). These statistics are collected across 100 runs in both "Situation"s.
| Relevant Log | **Metric**        | Same Subnet | Different Subnet | …
=> RSDK-6515 Add dial timeout and stats

lib/src/rpc/dial.dart
[RSDK-7376](https://viam.atlassian.net/browse/RSDK-7376)
Adds a couple more logs to dial code to indicate when local ICE candidates are generated and when remote ICE candidates are received from the signaling server (timestamps are already included in logs). Slight WIP, as I'd like to find a way to turn on verbose WebRTC logging, as well.
[RSDK-7376]: https://viam.atlassian.net/browse/RSDK-7376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-7376 Add more logs to dial

lib/src/robot/client.dart
Note to reviewers: we currently have no testing set up for a robot client. It seems that adding some would necessitate either changing the `RobotClient` type to add new constructors, or a bit of digging/fiddling. I imagine this is why we didn't add tests in the past.
Given how trivial this method is to implement, I opted to just add it and continue to punt on the testing question. Happy to discuss if there's disagreement.
=> RSDK-6665 - add getCloudMetadata client method

example/viam_example_app/lib/location_screen.dart, example/viam_example_app/lib/organization_screen.dart
I'm unsure if there is a code of conduct or a PR template for PRs but I'll post it as is.
I wanted to look at the SDK and I found the example app, most likely not up-to-date with the latest changes in the SDK.
So, here is a possible fix for it.
=> `viam_example_app` has syntax's errors

lib/src/app/robot.dart, lib/src/rpc/dial.dart, lib/src/viam_sdk.dart, lib/src/viam_sdk_impl.dart, lib/viam_sdk.dart, test/unit_test/app/app_robot_client_test.dart, test/unit_test/dial/dial_test.dart, test/unit_test/mocks/service_clients_mocks.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
[RSDK-7769](https://viam.atlassian.net/browse/RSDK-7769)
[RSDK-7770](https://viam.atlassian.net/browse/RSDK-7770)
Adds a wrapper for app's robot service and implements only the `log` method. Adds a `logOutput` option to dial options to allow specifying a custom log output.
To be used in [PR-LINK-TODO](https://github.com/viamrobotics/flutter-rc-app/pull/140) to allow the mobile app the send connection establishment logs to app.viam.com.
[RSDK-7769]: https://viam.atlassian.net/browse/RSDK-7769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RSDK-7770]: https://viam.atlassian.net/browse/RSDK-7770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RSDK-7769, RSDK-7770 Add AppRobotClient and LogOutput dial option

lib/src/components/gripper/gripper.dart, lib/src/components/motor/motor.dart, lib/src/components/power_sensor/power_sensor.dart, lib/src/components/servo/servo.dart
Also fixes my power sensor mistakes 👀
=> DOCS-2591: Add motor and servo example snippets

.github/workflows/release.yml, .github/workflows/update_protos.yml, Makefile, lib/src/rpc/dial.dart, lib/src/rpc/web_rtc/web_rtc_client.dart, lib/src/utils.dart, pubspec.yaml
How it works:
- `update-protos.yml` updates the `apiTag` value in the `getVersionMetadata` function
- `release.yml` updates the `sdkVersion` value in the `getVersionMetadata` function
- channels update their options to set `viam_client` equal to the output of `getVersionMetadata`
Note that this is a bit of a bummer because we're storing the SDK version in two places (`pubspec.yml` and `utils.dart`). I spent a good amount of time trying to find some alternative whereby we'd get the version info out of `pubspec.yml` instead. The potential solutions and (seemingly intractable) problems I encountered were:
- you can't read data out of `pubspec.yml` directly in a synchronous way, which means that reading `pubspec.yml` data would require polluting our API with async, which would be a …
=> RSDK-8304 - send version metadata

lib/src/rpc/web_rtc/web_rtc_client_connection.dart, lib/src/utils.dart, test/unit_test/utils/utils_test.dart
Fixes a bug whereby we were doubling timeout durations by putting the full value in both the `seconds` and `nanos` fields, which incidentally meant that we were getting an int overflow error when trying to pass a timeout of ~2sec or greater.
=> RSDK-8607 - fix timeout generation bug

doc/dependency_decisions.yml, lib/src/rpc/dial.dart, lib/src/rpc/web_rtc/web_rtc_client.dart
We weren't properly disconnecting WebRTC connections. Maybe because we didn't actually define shutdown behavior... 🤷‍♂️
[flyby] removing an unused class
=> Add shutdown function

lib/src/robot/client.dart
Ran into an issue with this where i wanted to set `enableSessions` to false - it was not possible because it was `final` and the value was set upon initialization.
An alternative approach could be leaving them as final, but providing the default values in the constructors.
=> make RobotClientOptions properties *not* final

lib/src/components/camera/service.dart, test/unit_test/components/camera_test.dart
- added support for `frame_rate` by returning it in getProperties in service.dart
- added a test in camera_test.dart to test for setting vs not setting `frame_rate`
=> RSDK-8812: Add frame_rate to flutter sdk

analysis_options.yaml, lib/src/app/app.dart, lib/src/app/billing.dart, lib/src/app/data.dart, lib/src/app/ml_training.dart, lib/src/app/robot.dart, lib/src/resource/manager.dart, lib/src/robot/client.dart, lib/src/rpc/web_rtc/web_rtc_client.dart, lib/src/rpc/web_rtc/web_rtc_client_connection.dart, lib/src/viam_sdk_impl.dart, lib/widgets/camera_stream.dart, lib/widgets/joystick.dart, lib/widgets/multi_camera_stream.dart, lib/widgets/resources/arm.dart, lib/widgets/resources/base.dart, lib/widgets/resources/board.dart, lib/widgets/resources/gripper.dart, lib/widgets/resources/motor.dart, lib/widgets/resources/sensor.dart, lib/widgets/resources/servo.dart, test/unit_test/components/sensor_test.dart
I am proposing adding 2 new lint rules to our dart codebases.
https://dart.dev/tools/linter-rules/prefer_relative_imports
https://dart.dev/tools/linter-rules/directives_ordering
This lint will enforce the following order in the imports
1. dart imports
2. flutter package imports
3. relative emports
4. exports and parts
As well as enforcing alphabetical order inside those sections.
will enforce using relative import for any files imported from lib/ - which paired with order_directives will ensure local imports are always listed after external imports.
---
This PR does not make any functional changes, just re organizes imports and adds lint rules to support the pattern moving forward.
This is the same pattern we are following for our mobile app repos, the consistency across all dart repos …
=> [refactor] order imports & prefer local import

analysis_options.yaml
These two lints have been deprecated. Removing.
> 'avoid_returning_null' was removed in Dart '3.3.0'
> Remove the reference to 'avoid_returning_null'.
> 'avoid_returning_null_for_future' was removed in Dart '3.3.0'
> Remove the reference to 'avoid_returning_null_for_future'.
=> Remove deprecated lints

lib/src/rpc/web_rtc/web_rtc_client.dart
before this change If I disabled sessions in dialOptions I would get an error whenever making a call to a robot.
```
gRPC Error (code: 2, codeName: UNKNOWN, message: invalid UUID length: 0, details: [], rawResponse: null, trailers: {})
```
=> Do not send empty session id when sessions disabled

lib/src/app/data.dart, pubspec.yaml, test/unit_test/app/data_client_test.dart
For context: The return type of the TabularDataBySQL/MQL proto has changed to return both a list of structs, the existing return type, and also a list of bytearrays that represent BSON.
Added a required dependency to bson to use the BSON library for dart
BSON provides a` BsonCodec.deserialize()` and `BsonCodec.serialize()` function for converting lists of byte sequences into lists of dart objects.
Testing:
Updated the `data` testing input to include `DateTime` objects, as the Flutter SDK will receive date fields in this format. I added a check to ensure that `DateTime` inputs are returned as native Flutter `DateTime` objects
I ensured that date fields are returned as native dart DateTime objects instead of strings by running tabularDataByMQL against real tabular data on viam-dev and …
=> RSDK-9180: Change TabularDataBySQL/MQL return type to raw BSON in Flutter SDK

lib/src/components/movement_sensor/client.dart, lib/src/components/sensor/client.dart, lib/src/utils.dart, test/unit_test/utils/utils_test.dart
Similar to how we do it in python: https://github.com/viamrobotics/viam-python-sdk/blob/8a1aef023ef2d77c4988c60e9de678aaac8e5bb8/src/viam/utils.py#L202
=> Convert sensor reading values to types

lib/widgets/camera_stream.dart
Was just using this widget in a way where the camera will be updated as a user cycles through a list of cameras. 
The camera was updating but the stream wouldn't restart because it only starts 1 time in `initState()`
=> Reset stream in camera_stream if camera changes

lib/src/media/stream/client.dart, lib/src/robot/client.dart
Adds handlers to the stream and robot client to hit options endpoints.
Tested using local flutter web app that fires the following code block.
```dart
final machine = await RobotClient.atAddress(
host,
RobotClientOptions.withApiKey(apiKeyID, apiKey),
);
final res = await machine.getStreamOptions("wc-cam");
print(res);
await machine.setStreamOptions("wc-cam", res[1].width, res[1].height);
await machine.resetStreamOptions("wc-cam");
await machine.close();
```
=> [RSDK-9250] - Add stream options handlers

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
We added a new Data endpoint GetLatestTabularData viamrobotics/app#6896, this PR adds the endpoint to Flutter SDK.
=> DATA-3398: Add GetLatestTabularData endpoint to Flutter SDK

lib/src/rpc/dial.dart
According to the [docs](https://pub.dev/packages/bonsoir), you need to start mDNS AFTER setting listeners
=> Start mdns after setting listeners

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart
This PR adds the new Data endpoint [ExportTabularData](https://github.com/viamrobotics/app/pull/6969/files) to the flutter SDK.
=> DATA-3446 Add exportTabularData to DataClient

example/viam_example_app/ios/Flutter/Debug.xcconfig
When trying to build `viam_example_app` for iOS you will encounter this error:
```
/bin/sh: /packages/flutter_tools/bin/xcode_backend.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
That's because the [failing script](https://github.com/viamrobotics/viam-flutter-sdk/blob/5eda81a7a55546447d07a793b05983154050d4e1/example/viam_example_app/ios/Runner.xcodeproj/project.pbxproj#L350) references `FLUTTER_ROOT` which is undefined
The `Generated.xcconfig` file defines `FLUTTER_ROOT` as well as [several other properties](https://github.com/jonataslaw/easy/blob/master/example/ios/Flutter/Generated.xcconfig). Including this in the `Debug.xcconfig` resolves the error
Encountered this error while pairing w/ @benjirewis when he was trying to run the example
=> Fix building example project for iOS

lib/src/services/vision.dart
Note to reviewer: Please advise if added code samples should use something other than "final"
=> DOCS-3354: Add links for vision service methods

lib/src/components/arm/arm.dart, lib/src/components/base/base.dart, lib/src/components/board/board.dart, lib/src/components/camera/camera.dart, lib/src/components/gantry/gantry.dart, lib/src/components/generic/generic.dart, lib/src/components/gripper/gripper.dart, lib/src/components/motor/motor.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/power_sensor/power_sensor.dart, lib/src/components/sensor/sensor.dart, lib/src/components/servo/servo.dart
Update links for new docs IA, add specific hashes, and add missing examples
=> DOCS-3351: Update Flutter SDK component links

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart
**BREAKING CHANGE**
We were missing the param to actually download the data. In the process of changing that, I had to change the return type of `binaryDataByIDs` since the user can request just the count now. 
As a flyby, I fixed `binaryDataByFilter` to actually use `countOnly`
=> Add includeBinary to data funcs

lib/src/services/discovery.dart, test/unit_test/services/discovery_test.dart
I had previously thought a `discoveryName` needed to be passed in to `discoverResources`. I realized while using this new method in flutter that I forgot to remove the input parameter after changing the function to use `this.name`.
=> RSDK-9622 FIX: fix discoverResources input parameters 

lib/src/app/data.dart
This PR adds an optional boolean for TabularDataByMQL. Typically, all user data is stored in blob storage, but now users can opt in storing their tabular data in a database for faster queries. This boolean allows users to specify which data source they would like to query from.
=> DATA-3759:  Update TabularDataByMQL to have optional bool for useRecentData

Makefile, example/viam_example_app/.gitignore, example/viam_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/viam_example_app/macos/Runner/AppDelegate.swift, lib/src/gen/google/protobuf/descriptor.pb.dart, lib/src/gen/google/protobuf/descriptor.pbenum.dart, lib/src/gen/google/protobuf/descriptor.pbjson.dart, lib/src/gen/grpc/reflection/v1/reflection.pb.dart, lib/src/gen/grpc/reflection/v1/reflection.pbenum.dart, lib/src/gen/grpc/reflection/v1/reflection.pbgrpc.dart, lib/src/gen/grpc/reflection/v1/reflection.pbjson.dart, lib/src/robot/client.dart, lib/src/robot/sessions_client.dart, lib/src/rpc/dial.dart, lib/src/rpc/web_rtc/web_rtc_client.dart
clone of https://github.com/viamrobotics/viam-python-sdk/pull/857
Updated the functionality to now use reflection to determine if a method is monitored. 
At the beginning of the session:
1. Get the list of services on the connected machine
2. For each service, get the list of methods
3. For each method, store whether it is monitored in a map
Then, when making a call:
1. Check to see if the method is monitored
2. Add metadata if monitored
Had to do it this way because we can't use reflection prior to making a call because reflection is async, and creating a call is sync. So We have to basically create a list of monitored methods at the very start.
This also fixes a subtle bug in the session client where it could exit the heartbeat task early because getting the metadata is async, but we …
=> Add actuating methods as a check

lib/src/robot/client.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
https://viam.atlassian.net/browse/RSDK-9633
assuming I'm not supposed to delete the gen files, but otherwise I am deleting DiscoverComponents from everywhere. 
api pr: https://github.com/viamrobotics/api/pull/638
=> [RSDK-9633] delete discover components

.github/workflows/update_protos.yml
Sets a new token for checkout step to cause tests to run during proto update workflow.
Unlike https://github.com/viamrobotics/viam-python-sdk/pull/864, we use `GIT_ACCESS_TOKEN` instead of `REPO_READ_TOKEN`. `REPO_READ_TOKEN` does not exist in this repo's secrets, and per @abe-winter the `GIT_ACCESS_TOKEN` _may_ work as well. If it does not, we can revisit.
=> RSDK-9901 - run tests in proto workflow

test/test_utils.dart, test/unit_test/components/arm_test.dart, test/unit_test/components/board_test.dart, test/unit_test/components/camera_test.dart, test/unit_test/components/gantry_test.dart, test/unit_test/components/gripper_test.dart, test/unit_test/components/motor_test.dart, test/unit_test/utils/utils_test.dart
Changes the logic for finding a port for tests to ensure that the found port is unused.
It's hard to be absolutely confident this is right, since the failure is flaky and hard to reproduce reliably. But, the logic of the change seems sound to me, and is cribbed from logic [used by dart internally](https://chromium.googlesource.com/external/github.com/dart-lang/test/+/master/pkgs/test_core/lib/src/util/io.dart#147) for testing. I figure if it's good enough for the dart team, it's probably good enough for us!
=> RSDK-9900 - always find unused port for testing

lib/src/robot/client.dart, lib/widgets/resources/switch.dart
Finish removal of `Discovery` types to allow for compilation to finish.
Also changes call for setting of a color's `alpha` value in the switch widget to be a setting of `opacity` instead (in line with how it's done in the `motor` widget).
=> finish discovery removal, change alpha setting for color

lib/src/app/app.dart, test/unit_test/app/app_client_test.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
(https://viam.atlassian.net/browse/CONSULT-940) - This PR adds a flutter sdk wrapper for listMachineSummaries. All of the changes in `test/unit_test/mocks/service_clients_mocks.mocks.dart` are generated code changes in order to build out a test in app_client_test.dart. In addition to adding tests to `app_client_test.dart` I tested locally using the viam_robot_example_app. 
@stuqdog, i updated the comment to be more clear about the what we are actually returning, but let me know if you still prefer to change name of function, not opposed
Here is a video below:
https://github.com/user-attachments/assets/6b832a6d-8782-415c-8642-9692eec34225
=> [CONSULT-940] add listMachineSummaries to flutter sdk

lib/src/app/app.dart, test/unit_test/app/app_client_test.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
Add user-defined metadata CRUD operations 
**See ticket [here](https://viam.atlassian.net/jira/software/c/projects/APP/boards/64?selectedIssue=RSDK-10127)**
=> [RSDK-10127] Add get and update metadata functions

lib/src/gen/app/datapipelines/v1/data_pipelines.pb.dart, lib/src/gen/app/datapipelines/v1/data_pipelines.pbjson.dart, lib/src/gen/app/v1/app.pb.dart, lib/src/gen/app/v1/app.pbjson.dart, lib/src/utils.dart
This is an auto-generated PR to update proto definitions. Check the commits to see which repos and commits are responsible for the changes
=> Automated Protos Update

lib/src/components/arm/client.dart, lib/src/components/base/client.dart, lib/src/components/board/client.dart, lib/src/components/button/client.dart, lib/src/components/camera/client.dart, lib/src/components/gantry/client.dart, lib/src/components/generic/client.dart, lib/src/components/gripper/client.dart, lib/src/components/motor/client.dart, lib/src/components/movement_sensor/client.dart, lib/src/components/power_sensor/client.dart, lib/src/components/sensor/client.dart, lib/src/components/servo/client.dart, lib/src/components/switch/client.dart, lib/src/resource/base.dart, lib/src/services/discovery.dart, lib/src/services/vision.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart, test/unit_test/services/discovery_test.dart, test/unit_test/services/vision_test.dart
Add trace debug logging. You can enable/disable trace logging by calling `enableDebugLogging` or `disableDebugLogging` on a client.
Caveat: You have to do it on a client. When you call `fromRobot`, you get the base class back. So you'll have to cast it.
```dart
final myArm = Arm.fromRobot(robot, "my-arm");
final armClient = myArm as ArmClient;
armClient.enableDebugLogging(traceKey: "arm-logger");
await armClient.move()
armClient.disableDebugLogging()
```
Got inspiration from
https://github.com/viamrobotics/viam-python-sdk/pull/747
https://github.com/viamrobotics/viam-typescript-sdk/pull/384
=> [RSDK-9110] Add trace debug logging

lib/src/app/provisioning.dart, lib/src/viam_sdk_impl.dart
Updates to use the ip `10.42.0.1` instead of a hostname `viam.setup` during provisioning. Using `viam.setup` while using cellular (but connected to the hotspot) on iOS does not work and the requests fail.
Also,
Testing in my [example project](https://github.com/viamrobotics/viam_flutter_provisioning_widget/tree/main/example/hotspot_provisioning), I couldn't get the init w/ api key to function (for provisioning): https://github.com/viamrobotics/viam_flutter_provisioning_widget/pull/2
I think the host `provisioning.viam` in this init for the `ProvisioningClient` is outdated / doesn't match how it's setup when using an access token (uses `viam.setup`). Plus we want to use an ip now here as well
=> Hardcode ip for provisioning, fix client used with apikey

lib/src/robot/client.dart
This request can be useful in the mobile apps for checking when added/removed cameras, sensors, other resources are [available or removed](https://github.com/viamrobotics/viam-flutter-sdk/blob/5e1c35c4c45ad0c939a3eb29af8fb8ee38d4d917/lib/src/gen/robot/v1/robot.pbenum.dart#L50) so we can communicate that better to users. 
May be better than calling [refresh](https://github.com/viamrobotics/viam-flutter-sdk/blob/5e1c35c4c45ad0c939a3eb29af8fb8ee38d4d917/lib/src/robot/client.dart#L115) and continuously checking for resources to be present there.
=> Add GetMachineStatus to RobotClient

lib/src/app/app.dart, test/unit_test/app/app_client_test.dart
Add a sendEmailInvite boolean to the resendOrganizationInvite() method, allowing us to control whether an email invite is sent when the invite is resent
=> Add sendEmailInvite parameter to resendOrganizationInvite

lib/src/app/provisioning.dart, test/unit_test/app/provisioning_client_test.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
(https://viam.atlassian.net/browse/APP-8734) - This PR adds a wrapper for the new exitProvisioning() call in the provisioning client, enabling it to be used in the mobile apps and the hotspot provisioning widget.
=> [APP-8732] Add exitProvisioning() wrapper to flutter SDK

lib/src/components/switch/client.dart, lib/src/components/switch/service.dart, lib/src/components/switch/switch.dart, lib/widgets/resources/switch.dart, test/unit_test/components/switch_test.dart
- Added getLabels() to Switch interface and SwitchClient
- Updated ViamSwitchWidget to display labels if available
=> Add support for retrieving and displaying Switch labels

lib/src/components/camera/camera.dart, lib/src/components/camera/client.dart, lib/src/components/camera/service.dart, lib/src/media/image.dart, test/unit_test/components/camera_test.dart
I wrote a demo web app Flutter client pinned to my local feature branch SDK. It calls a `image_file` camera on my local viam-server that has the new signature of `GetImages` implemented on the Go server side. I will be testing that filter source names indeed filters:
```
final machine = await RobotClient.atAddress(
host,
RobotClientOptions.withApiKey(apiKeyID, apiKey),
);
final imageFileCam = Camera.fromRobot(machine, "image-file-1") ;
final resp = await imageFileCam.getImages();
print("hi!");
print(resp.metadata!.capturedAt);
for (var img in resp.images) {
print(img.image.mimeType);
}
print("bye!");
await machine.close();
```
```
hi!
2025-08-29 17:41:49.282364Z
image/jpeg
image/jpeg
FORMAT_RAW_DEPTH
bye!
```
```
...
final resp = await imageFileCam.getImages(filterSourceNames: …
```
=> RSDK-11707    —     Update Flutter SDK with new GetImages signature

lib/src/rpc/dial.dart
I was exploring using `accessToken` like the Svelte SDK does for dialing a robot and realized if we don’t include `credentials` and it is `Null` we go down a weird code path.
As an aside, I think GrpcOrGrpcWebClientChannel doesn’t work for a `StreamManager` which is what happens currently happens prior to this change if users only set `accessToken` and not `credentials`. This feels like a bug that should be investigated.
=> Allow users to dial with only `accessToken` and no `credentials`

lib/src/rpc/web_rtc/web_rtc_transport_stream.dart
- Server never began emitting responses.
- Client timed out / cancelled.
- No server logs of the request payload in streaming case.
- Sent headers frame (no embedded request bytes).
- Then sent single request message frame with `eom = true` (end of protobuf message) but `eos = false` (NOT end of client stream). 
- Even if the RPC endpoint only specifies a streaming response, the cardinality of the request also becomes a stream.
- Because eos stayed false, the server‑streaming handler (which waits for the client to finish sending before producing outbound frames) never transitioned to “ready to send,” so the response stream never started.
```
rpc FetchStream(FetchStreamRequest) returns (stream FetchStreamResponse);
```
- Unary handlers optimistically process the first (only) request …
=> Handle eos marker for gRPC over WebRTC requests
