viamrobotics/viam-flutter-sdk

lib/src/components/servo/client.dart, lib/src/components/servo/servo.dart, lib/src/resource/registry.dart, lib/viam_sdk.dart
First cut at adding Servo Component client. 
Adds wrappers for servo component, I will add example app changes in a follow up MR, currently working on it.
=> RSDK-2830 - Servo component client first cut

example/viam_example_app/lib/main.dart, example/viam_example_app/lib/screens/servo.dart, lib/src/components/servo/client.dart, lib/src/components/servo/servo.dart, lib/src/resource/registry.dart, lib/viam_sdk.dart
This MR builds on top of https://github.com/viamrobotics/viam-flutter-sdk/pull/5 so please review that first.
Adds example view for servo component. Mimics app.viam.com but adds a move to section as well.
Also provides bounds checking and disables buttons if the move would move the servo out of bounds.
Testing:
https://user-images.githubusercontent.com/22106496/234365014-7c6152b3-66a2-4218-91d3-3071d74f9d9d.MOV
Bounds Checking
https://user-images.githubusercontent.com/22106496/234365052-35ccdaa6-b4ea-4f71-9a85-050d1f2875dd.MOV
Move To
https://user-images.githubusercontent.com/22106496/234365062-3e6914b3-651b-46c5-80d2-b648b2996913.MOV
=> RSDK-2830 - Servo example

lib/src/components/motor/client.dart, lib/src/components/motor/motor.dart, lib/src/resource/registry.dart, lib/viam_sdk.dart
First cut at the motor component wrapper
=> RSDK-2828 - first cut motor component

lib/src/components/servo/servo.dart
Add documentation comments to servo.dart.
I got these comments from the python sdk [servo.py](https://github.com/viamrobotics/viam-python-sdk/blob/main/src/viam/components/servo/servo.py)
=> RSDK-2830 - add servo documentation

example/viam_example_app/ios/Podfile.lock, example/viam_example_app/lib/main.dart, example/viam_example_app/lib/screens/motor.dart, example/viam_example_app/pubspec.lock
This PR adds an example screen for motors in the example app.
https://user-images.githubusercontent.com/22106496/236237245-12de6de0-6526-4dd4-b6e3-523c27313601.mov
=> RSDK-2828 - Add motor example

.vscode/settings.json, example/viam_example_app/lib/main.dart, example/viam_example_app/macos/Podfile.lock, example/viam_example_app/pubspec.lock, lib/src/domain/web_rtc/web_rtc_client/web_rtc_client.dart, lib/src/media/image.dart, lib/src/media/stream/client.dart, lib/src/robot/client.dart, lib/src/rpc/dial.dart, lib/src/utils.dart, lib/viam_sdk.dart, pubspec.yaml
Refactor WebRTC code and implement DialOptions
=> Refactor WebRTC

lib/src/components/arm/arm.dart, lib/src/components/arm/client.dart, lib/src/components/base/base.dart, lib/src/components/base/client.dart, lib/src/components/board/board.dart, lib/src/components/board/client.dart, lib/src/components/camera/camera.dart, lib/src/components/camera/client.dart, lib/src/components/motor/client.dart, lib/src/components/motor/motor.dart, lib/src/components/movement_sensor/client.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/sensor/client.dart, lib/src/components/sensor/sensor.dart, lib/src/resource/base.dart
And add default implementation of do command
=> Abstractify resource base name

lib/src/components/sensor/service.dart
tests will be added in a follow up, being tracked in RSDK-03281
=> RSDK-3123 - add sensor serverside

.vscode/settings.json, example/viam_example_app/lib/main.dart, lib/src/components/arm/arm.dart, lib/src/components/base/base.dart, lib/src/components/base/client.dart, lib/src/components/base/service.dart, lib/src/components/board/board.dart, lib/src/components/camera/camera.dart, lib/src/components/motor/motor.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/sensor/sensor.dart, lib/src/components/servo/client.dart, lib/src/components/servo/service.dart, lib/src/components/servo/servo.dart, lib/src/resource/base.dart, lib/src/robot/client.dart, test/unit_test/components/base_test.dart
Introduce tests for the Base resource, along with its service
=> [RSDK-3126] Base Service + Tests

lib/src/components/arm/arm.dart, lib/src/components/arm/client.dart, lib/src/components/arm/service.dart
tests will be added in a follow up, being tracked here https://viam.atlassian.net/browse/RSDK-3306
=> RSDK-3305 - arm server side first cut

lib/src/components/base/client.dart, lib/src/components/board/board.dart, lib/src/components/board/client.dart, lib/src/components/board/service.dart, pubspec.yaml
This PR adds the server side for Board.
Testing will be added in a follow up and is tracked here https://viam.atlassian.net/browse/RSDK-3283
=> RSDK-3124 - Board server side

lib/src/components/camera/service.dart
This PR adds the server side for camera. 
Testing will be added in a follow up, that is being tracked in https://viam.atlassian.net/browse/RSDK-3304
=> RSDK-3303 - first cut camera server side

lib/src/components/board/board.dart, lib/src/components/board/client.dart, lib/src/components/board/service.dart, test/test_utils.dart, test/unit_test/components/board_test.dart, test/unit_test/components/gantry_test.dart, test/unit_test/components/motor_test.dart
- FakeBoard
- Board Tests (FakeBoard, Server, Client)
- misc Board Client fixes the tests helped identify
- testing port helper function
=> RSDK-3283 - Board tests

lib/src/components/camera/client.dart, lib/src/components/camera/service.dart, lib/src/media/image.dart, test/unit_test/components/camera_test.dart
- add doCommand
- add FakeCamera
- Tests for FakeCamera, Client and service
- fix mimetype tostring
=> RSDK-3304 - camera tests

lib/src/rpc/dial.dart
there is a pre-existing wrapper class in the dart grpc package we are using that allows our SDK to compile for web (and still mobile) and use GRPC-web when needed. this change seamlessly adds web support to our flutter sdk.
https://pub.dev/documentation/grpc/latest/grpc_or_grpcweb/GrpcOrGrpcWebClientChannel-class.html
testing evidence :)
https://github.com/viamrobotics/viam-flutter-sdk/assets/22106496/e7fe476f-a5d1-406b-9906-afbb5f5ca3dc
=> add support for flutter-web and grpc-web

.github/workflows/test.yaml, Makefile, lib/src/app/data.dart, lib/src/gen/app/cloudslam/v1/cloud_slam.pb.dart, lib/src/gen/app/cloudslam/v1/cloud_slam.pbjson.dart, lib/src/gen/app/packages/v1/packages.pb.dart, lib/src/gen/app/packages/v1/packages.pbjson.dart, lib/src/gen/app/v1/app.pb.dart, lib/src/gen/app/v1/app.pbjson.dart, lib/src/viam_sdk.dart, lib/src/viam_sdk_impl.dart, lib/viam_sdk.dart, test/unit_test/app/app_client_test.dart, test/unit_test/app/data_client_test.dart, test/unit_test/mocks/service_clients_mocks.dart, test/unit_test/mocks/service_clients_mocks.mocks.dart
Add the data client. Currently only contains the 3 functions that DoR were using.
=> Data client

lib/src/di/di_clients/di_web_rtc_client.dart, lib/src/domain/web_rtc/web_rtc_client/web_rtc_client.dart, lib/src/robot/client.dart, lib/src/robot/sessions_client.dart, lib/src/rpc/dial.dart
This PR adds sessions to the flutter SDK.
Testing Evidence:
https://github.com/viamrobotics/viam-flutter-sdk/assets/22106496/211ca662-2dd6-462d-a1cb-8c36cff225da
=> RSDK-3057 - Sessions

CHANGELOG.md, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/viam_sdk_impl.dart, lib/src/widgets/widgets.dart, pubspec.yaml
Removed CHANGELOG.md because we don't keep that up to date
=> Prepare for publish

.github/workflows/update_protos.yml, Makefile
`sed` on macos works a little differently than `gnu sed`
=> Add workflow to update protos

.github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/release_candidate.yml, Makefile
Basically copied from the typescript SDK
=> [RSDK-4266] Add workflows for bumping versions and releasing

lib/widgets/resources/base.dart, lib/widgets/resources/sensor.dart
Using these widgets in prod revealed some changes that needed to be made.
=> Update views for use in prod

lib/src/robot/client.dart, lib/src/robot/sessions_client.dart
Add the ability to close robot connections and terminate running tasks.
=> Close robot connections

lib/src/app/app.dart, lib/src/app/data.dart, lib/src/errors.dart, lib/src/media/image.dart, lib/src/media/stream/client.dart, lib/src/resource/base.dart, lib/src/resource/manager.dart, lib/src/resource/registry.dart, lib/src/robot/client.dart, lib/src/robot/sessions_client.dart, lib/src/rpc/dial.dart, lib/src/viam_sdk.dart, lib/widgets/camera_stream.dart, pubspec.yaml
The current score of our SDK on pub.dev is only 110 out of 140. Adding documentation will help.
=> Documentation

lib/widgets/camera_stream.dart, lib/widgets/resources/base.dart
Show error for camera view when an error is received (instead of just logging it)
=> [APP-2377] Show camera errors

lib/src/components/gantry/gantry.dart, lib/src/components/gripper/client.dart, lib/src/components/gripper/gripper.dart, lib/src/components/gripper/service.dart, lib/src/resource/registry.dart, lib/viam_sdk.dart, lib/widgets.dart, lib/widgets/multi_camera_stream.dart, lib/widgets/resources/base.dart, lib/widgets/resources/gripper.dart, test/unit_test/components/gripper_test.dart
Add gripper as an available component, and also add its widget.
Also:
* Extract the camera stream and picker widget into its own component so it can be reused
=> [RSDK-4323] Gripper

example/viam_example_app/macos/Runner.xcodeproj/project.pbxproj, example/viam_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/widgets/resources/board.dart, lib/widgets/resources/sensor.dart
=> [RSDK-4325] Board widget

README.md, example/viam_example_app/README.md, example/viam_example_app/lib/main.dart, lib/src/robot/client.dart, lib/src/rpc/dial.dart
[APP-2521](https://viam.atlassian.net/browse/APP-2521)
TODO:
- check if there are other callsites to update
[APP-2521]: https://viam.atlassian.net/browse/APP-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APP-2521: SDK: Update Flutter code sample authing with API key

lib/src/app/app.dart, lib/widgets/resources/sensor.dart
Add a function to get logs for a robot part by page.
flyby: Fix variable name
=> Add new logging function

lib/widgets/resources/sensor.dart
Wasn't showing minutes before 🤦‍♂️
=> Fix sensor date format

Makefile, example/viam_example_app/lib/screens/base.dart, example/viam_example_app/lib/screens/gripper.dart, lib/widgets.dart, lib/widgets/resources/base.dart, lib/widgets/resources/board.dart, lib/widgets/resources/gripper.dart, lib/widgets/resources/motor.dart, lib/widgets/resources/servo.dart
* Rename `Screen` to be `Widget` since they are no longer full screens
* Add Servo widget
* Remove spacers, expandables, and scroll views. Let the embedding client handle that
=> Ready widgets to be expanded

lib/widgets/camera_stream.dart
Set the stream height appropriately for the camera widget
=> Set correct ratio for camera stream widget

example/viam_example_app/ios/Podfile, example/viam_example_app/ios/Runner/Info.plist, example/viam_example_app/macos/Flutter/GeneratedPluginRegistrant.swift, example/viam_example_app/macos/Runner.xcodeproj/project.pbxproj, example/viam_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/rpc/dial.dart, lib/src/rpc/grpc/grpc_or_grpcweb_channel.dart, lib/src/rpc/grpc/grpc_or_grpcweb_channel_grpc.dart, lib/src/rpc/grpc/grpc_or_grpcweb_channel_web.dart, pubspec.yaml
Add MDNS support to the Flutter SDK. 
I had to add our own version of the GrpcOrGrpcWebChannel wrappers to continue to allow web support.
=> RSDK-5141 - Add MDNS support

example/viam_robot_example_app/lib/main.dart, example/viam_robot_example_app/lib/screens/power_sensor.dart, example/viam_robot_example_app/lib/screens/screens.dart, lib/src/resource/registry.dart, lib/viam_sdk.dart
Adds power sensor screen. Also flyby readability change to clean up importing the screens.
=> RSDK-5561 - add power sensor screen

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart
Replace use of mqlQuery in favor of mqlBinary.
=> [RSDK-5873] Update TabularDataByMQL to accept list of BSON docs

lib/src/components/movement_sensor/client.dart, lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/movement_sensor/service.dart, test/unit_test/components/movement_sensor_test.dart
Updating getAccuracy return type. 
Scope doc: [here](https://docs.google.com/document/d/1dbVI9njfMWXWg8B_wfRU9vCzi6pGQsgdwgqqjMB-Uhc/edit#heading=h.tcicyojyqi6c)
=> RSDK-6122: getAccuracy

example/viam_example_app/android/app/build.gradle, example/viam_robot_example_app/android/app/build.gradle
fly by, noticed these example things that needed cleaning up.
=> misc android changes

lib/src/app/app.dart, test/unit_test/app/app_client_test.dart
add a wrapper for getFragment.
=> RSDK-5953 - add getFragment wrapper

pubspec.yaml
the crash appears to be resolve din the latest version of bonsoir 
https://github.com/Skyost/Bonsoir/issues/81 issue that we were tracking in the bonsoir package
=> RSDK-6392 - Upgrade Bonsoir

example/viam_robot_example_app/macos/Podfile, example/viam_robot_example_app/macos/Runner.xcodeproj/project.pbxproj, example/viam_robot_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/rpc/dial.dart, lib/src/rpc/web_rtc/web_rtc_transport_stream.dart
Address this issue: https://github.com/viamrobotics/viam-flutter-sdk/issues/161
Also addresses an issue where mdns wasn't working with API keys
=> [RSDK-6863] webrtc message size

example/viam_example_app/macos/Podfile, example/viam_example_app/macos/Runner.xcodeproj/project.pbxproj, example/viam_example_app/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/components/arm/client.dart, lib/src/components/base/client.dart, lib/src/components/board/client.dart, lib/src/components/camera/client.dart, lib/src/components/gantry/client.dart, lib/src/components/generic/client.dart, lib/src/components/gripper/client.dart, lib/src/components/motor/client.dart, lib/src/components/movement_sensor/client.dart, lib/src/components/power_sensor/client.dart, lib/src/components/sensor/client.dart, lib/src/components/servo/client.dart, lib/src/resource/base.dart, lib/src/resource/registry.dart, lib/src/services/vision.dart
`VisionClient` was missing its resource methods. 
Also made `name` final for resource
=> Add VisionClient.fromRobot

lib/src/components/motor/client.dart, lib/src/components/motor/motor.dart, lib/src/components/motor/service.dart, test/unit_test/components/motor_test.dart
blocked by API changes that should be merged later today
all tests passing with local API changes
=> RSDK-7749: Add SetRPM to flutter SDK

lib/src/components/arm/arm.dart, lib/src/components/base/base.dart, lib/src/components/board/board.dart
Not sure of syntax on many of these Viam-specific types--apologies if this is super wrong.
=> DOCS-2031: Add arm, base, board example snippets

lib/src/viam_sdk.dart
fly by noticed a copy pasta error
=> fix documentation comment

lib/src/rpc/dial.dart
flyby while working on something else. Noticed a lint suggestion to add const here. small optimization.
=> flyby fix lint suggesting const

lib/src/components/movement_sensor/movement_sensor.dart, lib/src/components/servo/servo.dart
* just a couple of updates, missing code sample and more information on one
=> DOCS-2951: Make updates from components QA

lib/src/rpc/web_rtc/web_rtc_client.dart
Addendum to https://github.com/viamrobotics/viam-flutter-sdk/pull/277
=> Fix sending session client over webrtc

lib/src/robot/client.dart, lib/src/robot/sessions_client.dart
If sessions aren't implemented on the receiving end, this will disable session support. Hearbeats will no longer be sent.
=> Improved error handling in sessions

lib/src/media/stream/client.dart
Should fix an error where streams were not automatically getting reset on a reconnection
=> Update how streams are re-added

lib/src/robot/client.dart
The [previous hotfix](https://github.com/viamrobotics/viam-flutter-sdk/pull/302) introduced a different bug -- if RDKs weren't sending back `local_name` and `remote_path`, we would strip the `remote_path` from the search but not the `local_name`.
Anyway, this PR adds both fields as default, the same way we do for creating resource names on subtype.
=> Add default local name and remote path

.github/workflows/update_protos.yml
=> RSDK-9901 - use git-access-token

lib/src/gen/app/data/v1/data.pb.dart, lib/src/gen/app/data/v1/data.pbgrpc.dart, lib/src/gen/app/data/v1/data.pbjson.dart, lib/src/utils.dart
This is an auto-generated PR to update proto definitions. Check the commits to see which repos and commits are responsible for the changes
=> Automated Protos Update

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart
Changes include: update to the flutter sdk functions for ExportTabularData and GetLatestTabularData as well as additions/modifications of test cases
=> DATA-4295: SDK/CLI changes to support ExportTabularData and GetLatestTabularData

lib/src/app/data.dart, test/unit_test/app/data_client_test.dart
Context: https://viam.atlassian.net/browse/DATA-4317
Forgive me: I've never even read flutter code before, let alone written a single line so if this is broken...blame the system.
Also, how does one go about making sure I didn't break anything here?
=> DATA-4317: Added DatasetIDs as Input to data_client

.github/workflows/ai-updater.yml
This adds the AI updater workflow to the Flutter SDK to automatically generate code when a proto update happens.
View the README in the AI Updater Repo (which this workflow calls) for more info.
=> RSDK-11492: Add AI Updater Workflow
